- name: "type: bug"
  color: "d73a4a"
- name: "type: feature"
  color: "a2eeef"
- name: "type: compat"
  color: "0e8a16"
- name: "type: adapter"
  color: "5319e7"
- name: "type: docs"
  color: "0075ca"
- name: "help wanted"
  color: "128a0c"
- name: "good first issue"
  color: "7057ff"
- name: "needs triage"
  color: "fbca04"
- name: "needs info"
  color: "fef2c0"
- name: "area: core"
  color: "cfd3d7"
- name: "area: pcan"
  color: "cfd3d7"
- name: "area: kvaser"
  color: "cfd3d7"
- name: "area: socketcan"
  color: "cfd3d7"
- name: "area: zlg"
  color: "cfd3d7"
