blank_issues_enabled: false
contact_links:
  - name: Questions & usage help
    url: https://github.com/pkuyo/CanKit/discussions
    about: Please ask questions in Discussions instead of opening an issue.