<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>$(CanKitTransportIsoTpVersion)</Version>
        <IsPackable>false</IsPackable>
        <Description>Experimental unfinished ISO-TP transport prototype; not supported for production use.</Description>
        <PackageTags>CAN;can bus;CANFD;ISOTP;CanKit;experimental</PackageTags>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>$(CanKitSharedFileVersion)</FileVersion>
        <Authors>Pkuyo</Authors>
        <RepositoryUrl>https://github.com/pkuyo/CanKit</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Configurations>Debug;Release;Fake</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseLocalProjectReferences)'=='true'">
        <ProjectReference Include="..\..\core\CanKit.Core\CanKit.Core.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(UseLocalProjectReferences)'!='true'">
        <PackageReference Include="CanKit.Core" Version="$(CanKitCoreDependencyVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="buildTransitive\**\*.*" Pack="true" PackagePath="buildTransitive\"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>
