using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using CanKit.Abstractions.SPI.Registry.Core;

namespace CanKit.Core.Registry;

/// <summary>
/// Collects statically generated CanKit component registrations before the registry is initialized.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public static class CanRegistryBootstrap
{
    private static readonly object Sync = new();
    private static readonly Dictionary<string, AdapterRegistration> Adapters =
        new(StringComparer.OrdinalIgnoreCase);
    private static readonly Dictionary<string, ExtensionRegistration> Extensions =
        new(StringComparer.OrdinalIgnoreCase);
    private static bool _frozen;

    /// <summary>Adds an adapter registration generated by a CanKit adapter package.</summary>
    public static void AddAdapter(string name, Func<ICanRegister> factory, int order = 0)
    {
        if (string.IsNullOrWhiteSpace(name)) throw new ArgumentException("An adapter name is required.", nameof(name));
        if (factory is null) throw new ArgumentNullException(nameof(factory));

        lock (Sync)
        {
            ThrowIfFrozen();
            if (Adapters.TryGetValue(name, out var existing))
            {
                if (existing.Factory == factory && existing.Order == order) return;
                throw new InvalidOperationException($"Adapter registration '{name}' has already been added.");
            }

            Adapters.Add(name, new AdapterRegistration(name, factory, order));
        }
    }

    /// <summary>Adds a transport or protocol registration generated by a CanKit extension package.</summary>
    public static void AddExtension(string name, Func<ICanRegistryEntry> factory, int order = 0)
    {
        if (string.IsNullOrWhiteSpace(name)) throw new ArgumentException("An extension name is required.", nameof(name));
        if (factory is null) throw new ArgumentNullException(nameof(factory));

        lock (Sync)
        {
            ThrowIfFrozen();
            if (Extensions.TryGetValue(name, out var existing))
            {
                if (existing.Factory == factory && existing.Order == order) return;
                throw new InvalidOperationException($"Extension registration '{name}' has already been added.");
            }

            Extensions.Add(name, new ExtensionRegistration(name, factory, order));
        }
    }

    internal static RegistrationSnapshot Freeze()
    {
        lock (Sync)
        {
            _frozen = true;
            return new RegistrationSnapshot(
                Adapters.Values
                    .OrderBy(item => item.Order)
                    .ThenBy(item => item.Name, StringComparer.OrdinalIgnoreCase)
                    .ToArray(),
                Extensions.Values
                    .OrderBy(item => item.Order)
                    .ThenBy(item => item.Name, StringComparer.OrdinalIgnoreCase)
                    .ToArray());
        }
    }

    private static void ThrowIfFrozen()
    {
        if (_frozen)
            throw new InvalidOperationException("CanKit registrations must be added before CanRegistry is initialized.");
    }
}

internal sealed class AdapterRegistration
{
    internal AdapterRegistration(string name, Func<ICanRegister> factory, int order)
    {
        Name = name;
        Factory = factory;
        Order = order;
    }

    internal string Name { get; }
    internal Func<ICanRegister> Factory { get; }
    internal int Order { get; }
}

internal sealed class ExtensionRegistration
{
    internal ExtensionRegistration(string name, Func<ICanRegistryEntry> factory, int order)
    {
        Name = name;
        Factory = factory;
        Order = order;
    }

    internal string Name { get; }
    internal Func<ICanRegistryEntry> Factory { get; }
    internal int Order { get; }
}

internal sealed class RegistrationSnapshot
{
    internal RegistrationSnapshot(AdapterRegistration[] adapters, ExtensionRegistration[] extensions)
    {
        Adapters = adapters;
        Extensions = extensions;
    }

    internal AdapterRegistration[] Adapters { get; }
    internal ExtensionRegistration[] Extensions { get; }
}
