name: CI-adapter-Zlgcan

on:
  push:
    paths:
      - 'src/CanKit.Core/**'
      - 'src/CanKit.Adapter.ZLG/**'
      - 'tests/CanKit.Tests/**'
  pull_request:
    paths:
      - 'src/CanKit.Core/**'
      - 'src/CanKit.Adapter.ZLG/**'
      - 'tests/CanKit.Tests/**'
jobs:
  windows:
    name: Zlgcan (windows) – ${{ matrix.tfm }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        tfm: [net8.0, net48]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Configure endpoints
        shell: pwsh
        run: |
          "CANKIT_TEST_ADAPTERS=CanKit.Adapter.Zlgcan" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Restore
        run: dotnet restore CanKit.sln

      - name: Test (${{ matrix.tfm }})
        run: dotnet test CanKit.sln -c Release -f ${{ matrix.tfm }} --logger "trx;LogFileName=TestResults-${{ matrix.tfm }}.trx"

      - name: Upload Test Results (${{ matrix.tfm }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows-${{ matrix.tfm }}
          path: '**/TestResults-${{ matrix.tfm }}.trx'
